# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftransport.proto\x12\x0etransportProto\x1a\x1bgoogle/protobuf/empty.proto\"\x1a\n\x0bSendRequest\x12\x0b\n\x03\x63sv\x18\x01 \x01(\x0c\"+\n\x19GetRecommendedFeedRequest\x12\x0e\n\x06userId\x18\x01 \x01(\x03\"-\n\x1aGetRecommendedFeedResponse\x12\x0f\n\x07videoId\x18\x01 \x03(\x03\x32\xc7\x01\n\x10TransportService\x12\x44\n\x0bSendCSVFile\x12\x1b.transportProto.SendRequest\x1a\x16.google.protobuf.Empty\"\x00\x12m\n\x12GetRecommendedFeed\x12).transportProto.GetRecommendedFeedRequest\x1a*.transportProto.GetRecommendedFeedResponse\"\x00\x42\x12Z\x10.;transportProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transport_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\020.;transportProto'
  _globals['_SENDREQUEST']._serialized_start=64
  _globals['_SENDREQUEST']._serialized_end=90
  _globals['_GETRECOMMENDEDFEEDREQUEST']._serialized_start=92
  _globals['_GETRECOMMENDEDFEEDREQUEST']._serialized_end=135
  _globals['_GETRECOMMENDEDFEEDRESPONSE']._serialized_start=137
  _globals['_GETRECOMMENDEDFEEDRESPONSE']._serialized_end=182
  _globals['_TRANSPORTSERVICE']._serialized_start=185
  _globals['_TRANSPORTSERVICE']._serialized_end=384
# @@protoc_insertion_point(module_scope)
