# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import transport_pb2 as transport__pb2


class TransportServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendCSVFile = channel.unary_unary(
                '/transportProto.TransportService/SendCSVFile',
                request_serializer=transport__pb2.SendRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetRecommendedFeed = channel.unary_unary(
                '/transportProto.TransportService/GetRecommendedFeed',
                request_serializer=transport__pb2.GetRecommendedFeedRequest.SerializeToString,
                response_deserializer=transport__pb2.GetRecommendedFeedResponse.FromString,
                )


class TransportServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendCSVFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecommendedFeed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransportServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendCSVFile': grpc.unary_unary_rpc_method_handler(
                    servicer.SendCSVFile,
                    request_deserializer=transport__pb2.SendRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetRecommendedFeed': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecommendedFeed,
                    request_deserializer=transport__pb2.GetRecommendedFeedRequest.FromString,
                    response_serializer=transport__pb2.GetRecommendedFeedResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'transportProto.TransportService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TransportService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendCSVFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transportProto.TransportService/SendCSVFile',
            transport__pb2.SendRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRecommendedFeed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transportProto.TransportService/GetRecommendedFeed',
            transport__pb2.GetRecommendedFeedRequest.SerializeToString,
            transport__pb2.GetRecommendedFeedResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
